### ISSUE TITLE
Per-app access to FCM toggle doesn't make much sense

### ISSUE THREAD

**Issue by thestinger** [eylenburg/eylenburg.github.io#10]
You can control which apps have access to Play services on GrapheneOS via user and work profiles, since Play services isn't included in GrapheneOS and you choose where to install it. Specifically controlling whether FCM is available wouldn't be useful since there are many APIs, not only FCM. It's **broken** to have a Play services implementation present and to deny access to FCM. Many apps will avoid using their own push implementation when they detect Play services and then denying them access to FCM will break their push messaging. Doing this properly requires hiding Play services from them, which is currently accomplished via user or work profiles. GrapheneOS plans to add App Communication Scopes to eliminate this as one of the last reasons to use work profiles (user profiles have more use cases) but it's a complex feature to do properly.

**Comment by thestinger** [comment]
We have the location rerouting feature and plan to add more similar features, and some of those could be made per-app if it makes sense. There's no way for FCM to work without using the actual FCM service though, and it's up to the app's service how they use it such as Signal sending empty messages without any data/metadata. Some apps end-to-end encrypt the data they send through it while other apps send it directly and rely on FCM transport encryption. If you don't want apps to use FCM, you really need them cut off from Play completely without them able to see it or they are not going to use their own push since none are implemented that way in practice. They use FCM if Play is present, and if it's blocked then they just won't work properly.

**Comment by eylenburg** [comment]
I see the point you're making. For notifications you're right that the work profile or second user makes more sense. However there's also other features, e.g. the Maps API. So for example for Signal, without MicroG or Play Services it would use its own push service but have location services. With MicroG or Play Services, it would use FCM and have working location services. With MicroG but FCM registration disabled for the app, it would get working location services but (as you say) would lack notifications because it would still attempt to use FCM rather than its own push service. I suppose there might be _some_ app out there where this would be a desirable outcome - no notifications but something else fixed by MicroG - although Signal is of course a bad example because you'd rather have the push notifications and there's Signal-FOSS or Molly anyway. There are also some apps where you can decide which notification provider to use (e.g. Element has a setting and you can choose e.g. UnifiedPush/ntfy if it's installed). So if you run for example IodeOS you might think that you want to use MicroG for stuff like the Maps API or Safetynet, but you don't want Element to connect to FCM and use UnifiedPush instead so you block its FCM registration in the MicroG settings. But after all, I agree, it's a very niche use case, and in practice it's much better to use a work profile for Play Services or MicroG like you can do on GrapheneOS and DivestOS.

I deleted the row for "optional FCM registration?" and made a mention of it in the "can run in work profile?" row instead, with a tooltip explaining the issue you raised.

**Comment by thestinger** [comment]
> However there's also other features, e.g. the Maps API

That example involves more sensitive data: location data, looking up addresses, etc. For E2EE apps, they either encrypt the data they send via FCM or don't send any data through it at all like Signal and only use it to wake themselves. Ultimately it's up to the app what they send to third party services, and they can still use Google services including FCM without Google Play services. FCM can be used from desktop browsers, etc. too.

> There are also some apps where you can decide which notification provider to use

If that's the case, it really doesn't matter if FCM access is blocked. An app can always still contact Google services like FCM without Google Play services installed, Many Google services have official libraries to use them without Google Play services. FCM doesn't have an official Android library for that but does have cross-platform libraries you could use on Android with some work to add a foreground service, etc.

> I deleted the row for "optional FCM registration?" and made a mention of it in the "can run in work profile?" row instead, with a tooltip explaining the issue you raised.

Secondary users are also an option so 'user or work profile' makes more sense. GrapheneOS has cross-user notification forwarding as an option to make them more usable. Not sure if other OSes have applied that chnage.

**Comment by thestinger** [comment]
@eylenburg I'm not sure if the work profile line is correct. I'm not sure any of these OSes integrates microG in a way that it has cross-profile interact privilege, etc. but I'm not sure.

**Comment by thestinger** [comment]
@SkewedZeppelin knows more about the difference between how microG is implemented in DivestOS vs. the others. I wasn't aware of a difference with profiles. It's nearly unprivileged in DivestOS other than spoofing itself being Google Play vs. heavily privileged in CalyxOS and /e/OS compared to a regular app.

**Comment by eylenburg** [comment]
I'm not sure what you mean. The point I'm trying to make in that row now is "Can you decide that only apps A, B and C talk to Google, but not apps X, Y and Z?" The answer for GrapheneOS and DivestOS is "Yes, you can install Play Services/MicroG together with apps A, B and C in a separate user profile or work profile" and the answer for the others is "Kind of, you can deny access to FCM for apps X, Y and Z in the MicroG settings, but it may break functionality as these apps know Play Services are installed and will expect it to work", and for Stock Android it's "No, all apps can talk to Google".

**Comment by thestinger** [comment]
But can't you choose to only use microG in a certain work or user profile on those?

**Comment by eylenburg** [comment]
Very good point. I wasn't aware of it. It seems that this is possible with CalyxOS and IodeOS. Not sure about /e/; their MicroG seems to be more mandatory (you can disable it but they won't ask you if you want it when setting up your phone). But for now I just set them all to "Yes". 

For /e/ I added a question mark, and also did the same for a bunch of other where /e/ (or Iode) seem worse than LineageOS. For example @SkewedZeppelin write [here](https://divestos.org/misc/gnss.txt) that LineageOS has [removed](https://review.lineageos.org/q/I6254ef6e160ff0d3c3ce2e51f20f557e75826dff) the serial number for PSDS for Qualcomm chips  and I'd assume that this change has - or will - trickle down to /e/ and IodeOS.

**Comment by SkewedZeppelin** [comment]
@eylenburg 
I don't think it is optional on those other systems.

/e/OS comes with microG fully enabled out of the box. CalyxOS and iodeOS have it as an option to enable during the setup wizard.
If enabled they may be default enabled in any added work profile.

/e/OS will not inherit those location changes until after they stabilize on LineageOS 20.0 which is a current WIP for them, as they are still primarily on 19.1/A12.
iodeOS 4.x? should already have the location changes however.

**Comment by eylenburg** [comment]
Thank you @SkewedZeppelin 

I know that you can't deinstall MicroG on these as it's a system app, but you do have the option to disable it.

For CalyxOS I found some comments saying it is possible to have it only enabled in one profile but not the other:
[1] https://www.reddit.com/r/CalyxOS/comments/t6phv1/new_device_setup_multiple_profiles_microg/
[2] https://www.reddit.com/r/CalyxOS/comments/pkmxq7/run_microg_but_only_in_work_profile/

Not sure for IodeOS and /e/, I couldn't find any info. But I think on both you can "disable" the app in the settings, so possibly it can be disabled/enabled separately in the work/second and main profile. 


As for the location changes in LineageOS 20:
for "Some aftermarket systems allow the user to disable use of SUPL", "Some aftermarket systems allow the user to disable use of PSDS & XTRA", "Many aftermarket systems do not include the IMSI in SUPL requests", and "PSDS -> Qualcomm GPS chips -> removes serial number access" I will make IodeOS match LineageOS, and make a note for /e/ that it's "no" now but will come once they stabilize on LOS 20.
