### ISSUE TITLE
EXIF metadata stripping for photos in Calyx OS

### ISSUE THREAD

**Issue by jzaia18** [eylenburg/eylenburg.github.io#106]
The Android comparison list at https://eylenburg.github.io/android_comparison.htm has a slight inaccuracy in the "EXIF metadata stripping for photos" line for Calyx OS. While Calyx does not automatically strip EXIF metadata from photos (and as far as I am aware there is no way to make it do this automatically), it does come preinstalled with an app for stripping EXIF metadata: https://calyxos.org/docs/guide/apps/scrambled-exif/ . It might be more accurate to replace the "no" with something closer to "requires manual effort" or something to that effect.

**Comment by eylenburg** [comment]
I would agree. Bundled apps are not an OS feature unless it's some special app (like Seedvault) that won't run on other systems.
