### ISSUE TITLE
CalyxOS seems to now strip metadata from screenshots

### ISSUE THREAD

**Issue by matchboxbananasynergy** [eylenburg/eylenburg.github.io#11]
As per https://calyxos.org/news/2023/10/04/october-security-update/

>Put bare minimum metadata in screenshots (strip unique ID, software info, date and timezone info)

It might make sense to link to that with a "see here" hyperlink like is done for other things.

Similarly, for GrapheneOS which has a [dedicated section](https://grapheneos.org/features#private-screenshots) in the features page explaining how the feature works, what is stripped and where the toggle to adjust this behavior can be found, that section should be hyperlinked for added context.

I wasn't able to find more documentation on this CalyxOS' feature so it might not be something that has a toggle - all of the information available about it seems to be in that changelog only.

**Comment by eylenburg** [comment]
Thank you, that's updated now

**Comment by eylenburg** [comment]
Fair enough, I changed that too
