### ISSUE TITLE
clarifications for the Google Play compatibility section

### ISSUE THREAD

**Issue by thestinger** [eylenburg/eylenburg.github.io#16]
Whether the approach is optional should really be made into a dedicated row. This will also help by shortening the implementation names. GmsCompat is a short form name for our sandboxed Google Play compatibility layer. It would be better to change `GmsCompat (Google Play)` to `Sandboxed Google Play compatibility layer` (which is a reasonable length with optional as a separate row) and `Google binaries in FOSS sandbox` to `Proprietary apps in regular app sandbox` to clarify that what we provide is not a special sandbox for them since many people have that misconception. It's the regular app sandbox with our improvements to it applying the same way they do for other apps.

**Comment by eylenburg** [comment]
I made some changes to the wording and added a separate row showing whether it's optional or not
