### ISSUE TITLE
System app downgrade protection

### ISSUE THREAD

**Issue by thestinger** [eylenburg/eylenburg.github.io#17]
System app downgrade protection bypasses have been covered in the news a bit recently. https://www.esper.io/blog/android-system-app-downgrade-vulnerability-fix is a good article.

There's still a major hole in the standard Android implementation where it permits upgrading system apps to the same versionCode but AOSP does not increase the versionCode with each security update.

The value for GrapheneOS "Yes, for updates and boot with fs-verity" (green), DivestOS is "Yes, for updates and boot" (yellow) while everything else is "Incomplete for updates, missing at boot" (red) matching standard Android. The purpose of fs-verity is providing continuous verification.

This is **related** to whether verified boot properly covers system apps, but it would be possible to enforce verified boot for them without closing this hole and vice versa.

**Comment by thestinger** [comment]
Ah, I missed the name.

**Comment by thestinger** [comment]
Updated the issue text.

**Comment by eylenburg** [comment]
I added a line for this in the security section
