### ISSUE TITLE
GrapheneOS is providing longer than 1 year of extended support for 4th/5th generation Pixels

### ISSUE THREAD

**Issue by thestinger** [eylenburg/eylenburg.github.io#19]
We're currently providing extended support to fill the gap between end-of-life and the 5 year mark. For 4th and 5th generation flagship Pixels, that means they get 2 years of extended support. Since 6th generation onwards already have 5 years of full support, we don't provide extended support for them. The correct value for the field now depends on the device lifetime. If it gets 4 years of official support, there would be 1 year of extended support.

"Until 5 years from launch" is the best way to phrase it now. This will still be relevant after 5th generation Pixels are fully unsupported since any future Qualcomm device would currently have ~4 years.

**Comment by thestinger** [comment]
Pixel 4 has been end-of-life since after October 2022 and we're still providing updates. We've deciding porting the end-of-life devices to newer major yearly releases doesn't make sense due to the regressions, disruption and significant resources it would require combined with it encouraging people to keep using them. We mark devices extended support for the first update they've missed from the vendor and then legacy extended support once they're on an older major release branch than official GrapheneOS. Can see that at https://grapheneos.org/releases and https://grapheneos.org/faq#supported-devices.

We're trying to avoid encouraging users to keep using insecure devices without firmware and driver updates so there's a balance. Updating them to new major releases would encourage continuing to use them, and there isn't much benefit since there are high/critical severity unfixed firmware and driver issues which largely defeats the purpose of providing any updates at all. It's questionable providing any extended support at all, but we are, and longer than 1 year now for better or worse.

**Comment by eylenburg** [comment]
I updates this now to say "until 5 years from launch"

**Comment by thestinger** [comment]
Thanks.
