### ISSUE TITLE
GrapheneOS will support Android Auto in its next release

### ISSUE THREAD

**Issue by matchboxbananasynergy** [eylenburg/eylenburg.github.io#20]
More information/details on this can be found here:

https://grapheneos.social/@GrapheneOS/111665498981590978

Once the next release lands, the table should reflect "yes" for Android Auto compatibility.

**Comment by thestinger** [comment]
This is in the Stable channel now.

**Comment by thestinger** [comment]
https://grapheneos.org/releases#2023123000 was the release adding it, but didn't make it past the alpha channel due to a keyboard issue. The subsequent release is in stable now.

**Comment by eylenburg** [comment]
Thank you, I've updated this now

**Comment by eylenburg** [comment]
Done now
