### ISSUE TITLE
Please consider adding SimpleX to IM comparison

### ISSUE THREAD

**Issue by LaurentBonnaud** [eylenburg/eylenburg.github.io#25]
Hi,

this project seems interesting and probably deserves to be compared with the rest of IM software:

[https://simplex.chat/](https://simplex.chat/)

**Comment by eylenburg** [comment]
I'm keen on adding it as it seems to be one of the most private messengers, but I'm a bit too busy at the moment to start researching it. Any help is appreciated! But I have put it on my list of things to do one day.

**Comment by LaurentBonnaud** [comment]
Thanks!

**Comment by eylenburg** [comment]
I just added it :)

**Comment by LaurentBonnaud** [comment]
Thanks a lot!
