### ISSUE TITLE
Please consider reinstating information about LineageOS for microG

### ISSUE THREAD

**Issue by petefoth** [eylenburg/eylenburg.github.io#26]
Hi

I notice that you removed mention of [LineageOS for microG](https://lineage.microg.org/) in [your recent commit](https://github.com/eylenburg/eylenburg.github.io/commit/09b44a49724e390e93f64dfa5d1d9a2f2b2eb270)

I know that LineageOS do now support signature spoofing, allowing users to manually install microG, but they do not make builds which ***include*** microG. LineageOS for microG ***does*** do that, and will continue to do so, making it a useful 'alternative' to manually installing microG.

Thanks very much for your work on maintaing this site.

Pete Fotheringham
(Current maintainer of LineageOS for microG)

**Comment by eylenburg** [comment]
I added the link back now
