### ISSUE TITLE
GrapheneOS applies changes for Google's eUICC management app which result in it not sharing data with Google

### ISSUE THREAD

**Issue by thestinger** [eylenburg/eylenburg.github.io#27]
See https://grapheneos.org/releases#2024012600 which introduced these changes. It's no longer simply the regular Google eUICC management app integration. It's still disabled by default but no longer requires sandboxed Google Play and cannot share data with it. It doesn't communicate with Google servers unless the carrier is hosting with them, which would involve using their servers regardless.

**Comment by eylenburg** [comment]
Thank you, I have updated this and marked it green
