### ISSUE TITLE
inaccurate secure/verified boot entries for Windows, macOS and GNU/Linux

### ISSUE THREAD

**Issue by thestinger** [eylenburg/eylenburg.github.io#30]
None of these has a complete implementation of secure/verified boot, particularly Windows and regular Linux distributions. You're confusing supporting verifying part of the OS with a full implementation. Verifying only the kernel without verifying the kernel line or even the core OS is not really useful. The kernel doesn't provide useful functionality to users without userspace. Downgrade protection is also needed for this to work properly. Attestation is not the same thing as secure boot and should not be confused with it.

macOS has the most complete implementation of these 3 by far, but as can be seen by the fact it can simply be largely disabled within the OS without any user-facing warnings shown at boot or anything like that, it is not a real implementation yet.

**Comment by eylenburg** [comment]
Thank you for elaborating on this, I changed it.

**Comment by Jeroen0494** [comment]
Hi,

When using a unified kernel image (UKI), you can add the Linux kernel, initramfs and cmdline to a single image, and sign it with secure boot. https://wiki.archlinux.org/title/Unified_kernel_image

Linux also has support for dm-verity to secure the whole stack: https://wiki.archlinux.org/title/Dm-verity

I'm not aware of any distro doing this out of the box though.
