### ISSUE TITLE
Android has an always enabled built-in firewall and uses it to create the VPN service feature used to provide app-based firewalls

### ISSUE THREAD

**Issue by thestinger** [eylenburg/eylenburg.github.io#31]
The entry for Android is wrong. You're confusing whether there's a complex user-facing configuration interface included in the OS with whether there's a firewall. It also certainly doesn't require root. There are apps using the VPN service feature for filtering traffic and the OS provides blocking of leaks. The OS also implements features based on the firewall for data limits and restricting data access in various forms, which vary based on the variant of the OS.

**Comment by eylenburg** [comment]
Fair enough, I changed this to say "Yes"
