### ISSUE TITLE
Devices section is unhelpful in Android Comparison

### ISSUE THREAD

**Issue by UntrimmedParasail** [eylenburg/eylenburg.github.io#34]
Half of the rows are "older devices", but it's not mentioning the fact that it's only this way because the newer ones CAN'T be bootloader unlocked. So the orange rows are just misleading. Not to mention those devices with their "Stock" (not actually) android use their own android skins. E.g. Samsung uses oneUI, xiaomi doesn't have play services

**Comment by eylenburg** [comment]
I updated it to have a note for those manufacturers who don't allow bootloader unlocking anymore. I also added the name of the manufacturer ROM, if they don't use stock Android.
