### ISSUE TITLE
Excellent Work

### ISSUE THREAD

**Issue by JslinkyJ** [eylenburg/eylenburg.github.io#35]
I had been unable to find a raw data driven source for tabular comparisons. So this is a fine find indeed, I am still not sure exactly how I managed to come by it, but I am glad I did. I had to trudge through far too many thinly veiled sales pitch websites that promise this sort of content and then pull a bait and switch with their product. If you want to make a timeline of the evolution of this practice, then be my guest. Too many naive people nowadays are sourcing their technical information like mice to corporate cheese.

As a bit of a question/feedback: 
For your generated tables, would you consider adding a feature to manually collapse specific columns and rows? Your preset filters are useful, but to more easily digest visual comparison experience, I really do need to remove some excess information based on my interests. If there is a solution process I can follow, then please let me know. 

PS: 
I know that an easier solution would be to black out entire columns and rows, but I have not seen you fully do this, which is good. You have preset filters that eliminate rows and columns completely or black them out, but they are still only a selection of presets. 

For someone appreciative of your effort due to its objective presentation of raw data, I understandably am drawn to having more control over how the data is displayed. My goal is to get a subset of your tables into a condensed enough size that I can more easily look between examples across variables. Otherwise it is a bit too much scrolling and jumping to be maximally effective, at least in my opinion.

Lastly, it is rare that I find information displayed this way nowadays. What is your inspiration?

**Comment by eylenburg** [comment]
Hi, thank you for your kind words first of all!

I would like to implement this and other features. I was thinking of:
* Filtering for rows and columns
* Making the first column sticky (like the header row is now) when you scroll, unless the screen/browser width is too little and the first column would take up the whole width. (At the moment the tables should display without horizontal scrolling if you have a maximized browser window on a Full HD screen with 100% scaling.)

For second, I think I know how to do it (with CSS `sticky`) but I haven't got round to do it. As for the first, this is - as you say - only done for the browser comparison (hide columns) and the cloud/email comparison (remove rows). I think it would be nice to have full flexibility here but to be honest I'm not sure what's the easiest and most elegant way of solving it. Ideally I would want to do it just with CSS and no Javascript.

I'll leave this open in the hopes of a pull request from a kind stranger and as a reminder to myself.

**Comment by JslinkyJ** [comment]
It is not ‘elegant’, but you could consider selecting a row and column to produce:- shrinking of all contained text to nil- shrinking of one axis dimension to nilThese would potentially avoid the need to remove the column or row completely, which seems harder.Though I only speculate: You could take the ‘removed’ column or row and send it to the back as a layer, then move all other columns and rows to the front and shift them to overlap the data to be removed.Or you could wipe the data from that selection, but keep the table structure. Then copy and paste shift all remaining data over one column dimension. There will be empty cells at the periphery, but who cares.On Apr 11, 2024, at 9:44 AM, eylenburg ***@***.***> wrote:﻿
Hi, thank you for your kind words first of all!
I would like to implement this and other features. I was thinking of:

Filtering for rows and columns
Making the first column sticky (like the header row is now) when you scroll, unless the screen/browser width is too little and the first column would take up the whole width. (At the moment the tables should display without horizontal scrolling if you have a maximized browser window on a Full HD screen with 100% scaling.)

For second, I think I know how to do it (with CSS sticky) but I haven't got round to do it. As for the first, this is - as you say - only done for the browser comparison (hide columns) and the cloud/email comparison (remove rows). I think it would be nice to have full flexibility here but to be honest I'm not sure what's the easiest and most elegant way of solving it. Ideally I would want to do it just with CSS and no Javascript.
I'll leave this open in the hopes of a pull request from a kind stranger and as a reminder to myself.

**Comment by eylenburg** [comment]
First column is now sticky thanks to https://github.com/eylenburg/eylenburg.github.io/pull/67
