### ISSUE TITLE
Android table

### ISSUE THREAD

**Issue by SkewedZeppelin** [eylenburg/eylenburg.github.io#4]
- `Signing keys` should be `Keystore provisioning`
- Note the update speed for WebView: https://divestos.org/misc/ch-dates.txt
- iodeOS uses the Quad9 insecure variant which doesn't enforce DNSSEC: https://divestos.org/misc/i.txt
- GrapheneOS and CalyxOS both deblob to an extent, just not as much as DivestOS
- You covered SUPL, but not the PSDS serial number issue or other aspects: https://divestos.org/misc/gnss.txt
- GrapheneOS (and DivestOS) are the only ones with an actual robust network block mechanism, eg: this impacted the Lineage/Calyx restrictions: https://review.lineageos.org/q/topic:%2213-firewall-bypassable-vpn-fix%22
- update speed should be an actual number
  - eg. LineageOS is like 1-2 weeks, iodeOS is like a month, /e/OS is 2 months, CalyxOS is a week, GrapheneOS is <2 days, DIvestOS is 1-3 weeks depending on branch: https://divestos.org/misc/a-dates.txt
 - Extended support should be clarified:
   - DivestOS currently provides monthly ASB updates for seven versions of Android
     - DivestOS for example still provides working monthly updates to some 11+ year old devices such as the Galaxy Neuxs.
   - LineageOS provides monthly updates for three versions
   - GrapheneOS, CalyxOS, and iodeOS only provide updates for one branch in most cases
     - They may support a previous branch for extended support however
   - /e/OS currently does 11 and 12, has 10 in maintenance mode, and has 13 in testing
     - It should be noted that they haven't actually provided any ASB backports to 10 since 2023-02 despite them existing (I did many of them myself)
 - The supported devices section needs fixing
  - DivestOS does support a handful of Asus and Motorola devices along with LG, HTC, F(x)tec, Asus, Yandex, Razer, Nextbit, Essential, Wileyfox, Cyanogen, Lenovo, and ZTE
- /e/OS does actually ship some of their devices with locked bootloaders, however afaik they perform verified boot signing with test-keys: https://divestos.org/misc/e.txt
- GrapheneOS does actually support Play for NLP: https://grapheneos.org/usage#sandboxed-google-play
- You should also document whether systems supporting microG actually restrict the signature spoofing correctly: https://divestos.org/misc/mg.txt

**Comment by eylenburg** [comment]
Thank you, that is extremely helpful! I have made most of the changes now: https://github.com/eylenburg/eylenburg.github.io/commit/d30906f9e84f283e376631e5568f262ca067ac9f#diff-9dd531df70b85d3d9dba9f38d9f31dbdb0f8178bd2eac35e9662239acc2bc204

The only thing I didn't quite "get" is the robustness of e.g. the `INTERNET` permission in GrapheneOS and DivestOS vs the approach taken by the others with their firewalls. I could find some info on leaks while using VPNs or Private DNS but also comments that these issues have been fixed now.

**Comment by thestinger** [comment]
@eylenburg Network toggle in GrapheneOS/DivestOS blocks both direct (socket) and indirect access (APIs requiring INTERNET). The LineageOS toggles block direct access, and some special cases were made for DownloadManager, but they are inherently leaky without requiring collusion between apps. It would be possible to build fine-grained toggles on top of what GrapheneOS/DivestOS have via the Network toggle by **disabling the INTERNET permission** but permitting direct access that's filtered. On the other hand, implementing fine-grained toggles without a baseline that works doesn't actually work.

I also think that @SkewedZeppelin would agree that the table should not present DivestOS as having all the security features of GrapheneOS when many of them aren't present. I would suggest starting by changes the hardened kernel and hardened libc values to "Most" to imply it has most of what GrapheneOS does along with adding a Hardened SELinux policy one which I don't think applies to anything but GrapheneOS.

DivestOS use of hardened malloc and kernel hardening also varies by device.

There are many other issues with the current table, especially for GrapheneOS. I'll open another issue about it.

**Comment by thestinger** [comment]
Also, no operating provides ASB patches after end-of-life, only the AOSP and mainline Linux kernel subset of ASB patches. It should say "Incomplete security patches after EOL" not "ASB patches" which is wrong.

Only the latest major release of Android has full AOSP security patches. The vast majority of Moderate and Low severity AOSP patches are done in AOSP monthly, quarterly and yearly updates (particularly quarterly and yearly) and are not backported to older releases. Only the latest release (September monthly release of Android 13 QPR3, soon Android 14) has full security patches. It is not a positive thing to have older operating system versions supported.

It should not be portrayed as negative that GrapheneOS only supports the latest release. You can include it information, but it's neutral information at best. An OS with full security patches is on the Android 13 QPR3 September release.

The timing for CalyxOS, LineageOS, etc. is also missing the multi-month delays when devices move to new major OS versions. When Android 13 was released, it took over 2 months for CalyxOS to provide important security patches for Pixels. It takes ~2-3 months for CalyxOS and ~4-6 months for LineageOS. It should say "~1 week with ~2-3 month delays after major updates". ASB includes vendor patches. Unless you split it into ASB AOSP patches and full ASB patches, the current information is wrong. Also, as stated above, ASB AOSP patches are only a subset of AOSP patches.

**Comment by thestinger** [comment]
I opened https://github.com/eylenburg/eylenburg.github.io/issues/5. I hope we can agree on most of it.
