### ISSUE TITLE
Feature Request: Add Wire to IM Comparison?

### ISSUE THREAD

**Issue by stephen-smith** [eylenburg/eylenburg.github.io#44]
https://wire.com centralized, FOSS https://github.com/wireapp, with video and voice chat, mobile and desktop versions.  Last I heard they were working on federation internally.

I think the features are roughly on par with Signal, and I use both.  I'm not a power-user so I haven't explored any of their feature sets (or individual features) exhaustively.

Disclaimer: I have previously been employed (indirectly) by Wire Swiss Gmbh.

**Comment by eylenburg** [comment]
Not sure if it's worth adding them as they are not too widely used (compared to other FOSS messengers e.g. Telegram or Signal) nor do they have any killer features (like federation or use without account like Simplex). Every extra messenger added means a lot of maintenance burden.

**Comment by eylenburg** [comment]
>If you just focus on what’s popular, it’s a good start but it would amplify network effect.

True, but I also need to keep in mind that for everything I add, it will require "upkeep" forever. So I would only consider it if it is very popular (e.g. Telegram or Whatsapp) or is very interesting/unique despite not being popular (e.g. SimpleX or Delta-Chat)
