### ISSUE TITLE
/e/OS now supports Android Auto

### ISSUE THREAD

**Issue by sophia-behling** [eylenburg/eylenburg.github.io#45]
Starting with /e/OS version 2.0 released on 2024-05-16 it supports Android Auto. Sources:

- [Release Notes](https://gitlab.e.foundation/e/os/releases/-/blob/v2.0-t-release-notes/notes/v2.0.md)
- [Documentation](https://doc.e.foundation/support-topics/android-auto)

Please kindly adjust the comparison table accordingly :-)

**Comment by eylenburg** [comment]
Thank you for this, I'll update the table in the next few days!

**Comment by eylenburg** [comment]
Updated
