### ISSUE TITLE
Adjust `Secure TLS for SUPL?` for DivestOS

### ISSUE THREAD

**Issue by SkewedZeppelin** [eylenburg/eylenburg.github.io#46]
May update now uses the GrapheneOS TLSv1.2 patch for Tensor Pixels: https://divestos.org/pages/news#2024-05

https://github.com/eylenburg/eylenburg.github.io/blob/693c46769a4f2eb6aac4cb4658045d857189d278/android_comparison.htm#L889-L891

**Comment by eylenburg** [comment]
Updated

**Comment by SkewedZeppelin** [comment]
Thank you @eylenburg
