### ISSUE TITLE
CalyxOS: hardened webview

### ISSUE THREAD

**Issue by lucasmz-dev** [eylenburg/eylenburg.github.io#48]
CalyxOS has a hardened webview, with patches taken from Cromite.

Their Chromium implemented doesn't change the name though (but will the icon soon), which is something specified on the page, it is currently just referred to as "CalyxOS' Chromium".

**Comment by SkewedZeppelin** [comment]
Calyx's Cromite fork supports does not support CFI or MTE.

**Comment by lucasmz-dev** [comment]
I need to look into this further sometime, for now I'll close this. They should have a few privacy patches which don't go unappreciated. I suppose hardened can be understood differently. I need to check which ones apply to WebViews etc.
