### ISSUE TITLE
CalyxOS: MAC address randomization

### ISSUE THREAD

**Issue by lucasmz-dev** [eylenburg/eylenburg.github.io#49]
The info right now is not exactly inaccurate, though Calyx does expose a toggle under Settings > System > Other Options which takes the one from Developer Settings and exposes it as a regular setting for users. I also believe with future garlic-level this might be enabled by default, irrelevant for now though.

So, it might be worth it adding some extra info for Calyx in that regard.

**Comment by SkewedZeppelin** [comment]
Developer toggles should be avoided for use by end users.
This toggle also would provide no fine-grained control for where a user does not want such randomization.

**Comment by lucasmz-dev** [comment]
Hmm OK, I'll close this one for now.
