### ISSUE TITLE
Mobile OSes: UnifiedNLP

### ISSUE THREAD

**Issue by lucasmz-dev** [eylenburg/eylenburg.github.io#50]
Calyx doesn't use UnifiedNLP anymore as microG has removed it, and I think UnifiedNLP might've just died anyway.
Not sure about other OSes here, if they're running their own signed version, most likely they don't as well and the user can't revert to older versions where that was the case.

My suggestion would be to rename it to "microG".

**Comment by SkewedZeppelin** [comment]
UnifiedNlp used to be a standalone component, but was later merged into microG.
Maybe more accurate would be "microG/UnifiedNlp".

**Comment by lucasmz-dev** [comment]
@SkewedZeppelin you can't use it in more recent versions of microG though, calling it "unifiednlp" may cause some issues since it doesn't actually interact with the modules. 

On the other hand 0.2.7 is still the tagged, recommended version IIRC, which does do UnifiedNLP, but that's an old version and to be honest breaks a lot more rather than being somehow 'stable'. CalyxOS already bundles more updated (also built by them) versions of microG and so it is not possible to revert to using UnifiedNLP, it's all microG location settings.

**Comment by SkewedZeppelin** [comment]
Indeed, seems even microG just calls it Location now.

**Comment by eylenburg** [comment]
So is this essentially just a matter of renaming UnifiedNLP to MicroG Location?

**Comment by lucasmz-dev** [comment]
Yeah I suppose. Unless one of these does UnifiedNLP separately but I don't think so?

**Comment by eylenburg** [comment]
Updated
