### ISSUE TITLE
CalyxOS: Connectivity check

### ISSUE THREAD

**Issue by lucasmz-dev** [eylenburg/eylenburg.github.io#52]
This can also be disabled under Settings > Internet > Connectivity check. It is not possible to change the server, just enable/disable atm. Might be nice to note and add a not fully, but slightly green check.

**Comment by eylenburg** [comment]
I think it can be changed on any Android device (and no root needed) so having Google as the default provider isn't really a problem: https://mullvad.net/en/help/configure-connectivity-checks-on-android
