### ISSUE TITLE
Stock: USB data line control should note it is only possible with an external app

### ISSUE THREAD

**Issue by lucasmz-dev** [eylenburg/eylenburg.github.io#54]
This column I think is a bit weird, I don't think stock Android usually has control for this. I certainly don't remember that. LineageOS has some, CalyxOS has some too. I feel like it is better to maybe note that this is not usually available. I suppose the implementation may the same, so using AOSP components, but it is not available anywhere and I think that should be noted.

Calyx has Block all, allow only when unlocked, and never block, and defaults to allow only when unlocked.
Lineage is pretty much the same, though it mentions ADB and seems like a different implementation, on Calyx AFAIK, if someone has USB debugging enabled, USB restrictions rules get disabled temporarily, which makes sense.

My view would be that at least Calyx, should have it say "Yes" and stock or any other OS that doesn't implement this say "No" and then maybe Graphene have a greener bar for being a bit more involved with kernel stuff and all.

**Comment by lucasmz-dev** [comment]
That's valid, I think it's worth it to have a better view even with that, Stock android doesn't really have any actual exposed controls (well, not usually anyway) and so this column ATM so it might confuse the user into thinking somehow stock has any even if not great controls, or that the other ones don't have any, that's kind of unfair.

**Comment by lucasmz-dev** [comment]
When you say "LineageOS/CalyxOS" don't disable anything until the connection is closed when the screen is locked", how does it differ from your guys' GrapheneOS? Do you close a connection when the screen is locked? I found the wording to be a bit confusing here.

**Comment by lucasmz-dev** [comment]
I think then it makes sense to just set stock Android to red with a "only with external tools" text or similar. Needing an external app isn't the same as having it integrated with the OS, it's also something the user needs to *figure out.*

**Comment by lucasmz-dev** [comment]
I understand that the implementation is different and that GrapheneOS has a more involved implementation, which is very much pointing out. But on stock, using this feels hacky and not planned.

The only thing I'm asking here now is that stock in specific (since the other OSes I believe all have these controls exposed) has a comment (and maybe a change of colour?) on how this is only possible with external tools (e.g. Sentry).

This way the difference in implementation for the more secure GrapheneOS one is very much visible, but stock isn't marked as 'Ok'.

**Comment by eylenburg** [comment]
> At the end of the day, it makes sense to just set stock Android to red with a "only with external tools" text or similar. Needing an external app isn't the same as having it integrated with the OS, it's also something the user needs to _figure out_, and isn't the default.

I think that's a fair point. Maybe a way to show is to have stock in light red colour (possible but needs an app), Calyx in light green (as it's a real "feature" of the OS but ultimately just leverages the hidden abilities of stock Android), and Graphene in normal green as it adds additional features.

**Comment by lucasmz-dev** [comment]
I won't get into any further discussion on here; I only really wanted to raise a few things that caused a ??? in my mind as an user when looking at the comparasion hosted by eylenburg, and this is getting out of the point where I can say much more and I need to focus on a few things; so I'll unsubscribe from this

Anyways, have a nice one ^^
https://www.youtube.com/watch?v=xaPNR-_Cfn0

**Comment by eylenburg** [comment]
Thank you all for this really interesting discussion. I definitely learned a few new things. I will implement #60 in the next few days
