### ISSUE TITLE
CalyxOS: Hardware memory tagging

### ISSUE THREAD

**Issue by lucasmz-dev** [eylenburg/eylenburg.github.io#55]
It supports it, on supported devices. (which are the 8 series only ofc since it's a armv9 feature)

**Comment by lucasmz-dev** [comment]
As far as I know it's really an AOSP feature, so a lot of others here should also be marked as "Yes" as well; but I can only really say that for Calyx.

**Comment by SkewedZeppelin** [comment]
There are additional issues with this developer toggle.

For instance A14 will randomly sample programs with GWP-ASAN which bypasses MTE in that case:
https://developer.android.com/ndk/guides/gwp-asan#recoverable
> Recoverable GWP-ASan is enabled only on approximately 1% of app launches, rather than every application launch.

Additionally without fine grained toggles, apps like Orbot and Tor Browser cannot be used currently.
