### ISSUE TITLE
LineageOS: 'older devices only'

### ISSUE THREAD

**Issue by lucasmz-dev** [eylenburg/eylenburg.github.io#56]
Currently it states Lineage only supports older devices, but we do have an example of a more recent device which is supported by Lineage, the Xperia 1 V. https://wiki.lineageos.org/devices/pdx234/

**Comment by lucasmz-dev** [comment]
Oop! Also an OnePlus device. https://wiki.lineageos.org/devices/salami/

**Comment by eylenburg** [comment]
Thanks! And a Xiaomi from Jan 2023 also has support now. I'll add them to the table, I think anything released in 2023/24 counts as new.
