### ISSUE TITLE
SafetyNet Attestation API is almost fully removed and microG does not implement the Play Integrity API

### ISSUE THREAD

**Issue by thestinger** [eylenburg/eylenburg.github.io#57]
microG does not implement the current Play Integrity API, only the legacy SafetyNet Attestation API. The table currently treats them as one thing, which is wrong.

Only apps which have migrated to using the Play Integrity API in current versions of their app can use the SafetyNet Attestation API since January 2024. It's disabled for apps which have not moved to the Play Integrity API. There's simply leeway until January 2025 for old versions of apps which have already migrated. For the most part, apps are not keeping a SafetyNet Attestation API fallback in their app and server code. Even if they do, it will be disabled January 2025.

You could split this line of the table and remove SafetyNet Attestation API support in January 2025. It shouldn't simply be one line though, because it's mostly incorrect at the moment.

**Comment by eylenburg** [comment]
Thank you, I have updated the table to not show SafetyNet and only focus on Play Integrity
