### ISSUE TITLE
Differentiate more between GrapheneOS sandboxed Android Auto with minimal special access toggles vs. /e/OS privileged Android Auto support

### ISSUE THREAD

**Issue by thestinger** [eylenburg/eylenburg.github.io#58]
The GrapheneOS support for Android Auto is an extension of the sandboxed Google Play compatibility layer. It runs Android Auto in the normal app sandbox and uses the same kind of compatibility layer approach to eliminate most of the privileges it normally requires. It can't quite function that way, so there are toggles for granting it access to USB for wired Android Auto and access to wireless protocols for wireless Android Auto. GrapheneOS does not simply remove the need for most of the privileged permissions, but also strips down the ones that are required and granting by the special access toggles (off by default) by limiting them to only granting what's actually needed. For wired Android Auto, there's not really any privacy loss from granting it the special access since it essentially just gives it control of USB. Wireless requires giving it a lot of access to Bluetooth, etc. which is why it's a separate toggle. This does not require giving it a whole bunch of access to user data like the /e/OS approach by simply making it a privileged app that's automatically granted the privileged permissions it requests. They're just using the privileged Google Play integration approach for Android Auto. It's not at all the same thing.

**Comment by eylenburg** [comment]
Thank you, I highlighted the fact that it's sandboxed
