### ISSUE TITLE
WEI warning false positives

### ISSUE THREAD

**Issue by matchboxbananasynergy** [eylenburg/eylenburg.github.io#6]
It seems that the website brings up the "WEI warning" page the moment it detects a browser posing as Chrome, but that isn't Brave, as far as I can tell based on the brief look I took at the code.

As you can imagine, this leads to false positives and can give people the wrong idea about their own browser.

For example, I navigated to your site on Vanadium, which I don't believe enables WEI in any capacity or plans to (https://github.com/GrapheneOS/Vanadium/issues/345).

The warning might make people think it detects something other than the browser being used to browse the website.

Solution: the warning should either be removed, or re-phrased in a way that doesn't say "Your browser supports X" in a way that can be misconstrued in the wrong way.

**Comment by eylenburg** [comment]
Good point. I didn't know that Vanadium had this disabled. I've now added a bit at the bottom apologizing that this could be a false positive. In any case, the WEI warning is only on the homepage (my little piece of activism) and not on the content pages.

**Comment by notahomosapien** [comment]
By the way, WEI has been abandoned now yet the *Your browser supports Web Environment Integrity (WEI)...* warning is still shown.

**Comment by eylenburg** [comment]
Thank you, that is fixed now
