### ISSUE TITLE
USB data line control row is now inaccurate and should be split up in 4 separate rows with accurate information

### ISSUE THREAD

**Issue by thestinger** [eylenburg/eylenburg.github.io#60]
The standard Android feature doesn't disable USB data lines and does not disable the USB-C protocol. It only disables high level USB support (peripherals, gadgets). You can even still use DisplayPort via USB-C. The current label refers to data lines, so it's not accurate anymore. I propose splitting it up to properly cover this while acknowledging what LineageOS and AOSP do.

There can be 4 rows instead:

1) Disabling USB-C data

GrapheneOS (green): Default (while locked), [docs](https://grapheneos.org/features#usb-c-port-and-pogo-pins-control)

Other operating systems do not implement this. It involves hardware-specific driver changes.

2) Disabling USB-C charging with OS booted

GrapheneOS (green): Opt-in, [docs](https://grapheneos.org/features#usb-c-port-and-pogo-pins-control)

Other operating systems do not implement this. It involves hardware-specific driver changes.

3) Disabling pogo pins data

GrapheneOS (green): Default (while locked), [docs](https://grapheneos.org/features#usb-c-port-and-pogo-pins-control)

Other operating systems do not implement this. It involves hardware-specific driver changes.

4) Disabling USB connections

GrapheneOS (green): Default (while locked), hardware + software, [docs](https://grapheneos.org/features#usb-c-port-and-pogo-pins-control)

LineageOS and CalyxOS (light red): Opt-in, incomplete software-only

Hover text: Can only disable high level software attack surface. Cannot disable USB until after early boot. Lacks a way to block new USB connections without ending existing connections. The mode for disabling USB connections while locked continues allowing new connections until existing connections end, including a connection through another method such as a pogo pins USB connection to a stand.

AOSP (red): Device admin API

Hover text: Requires installing a device admin app like Sentry. Can only disable high level software attack surface. Cannot disable USB until after early boot. Lacks a way to block new USB connections without ending existing connections.

**Comment by eylenburg** [comment]
Hi, I just updated the table to be similar to your suggestions. I also linked to this Github issue in a tooltip because you shared some valuable information for those who want to know more.
