### ISSUE TITLE
Desktop Environment Comparison LXQt Window Manager

### ISSUE THREAD

**Issue by crftbt** [eylenburg/eylenburg.github.io#61]
Hello, appreciate all the time taken to compile and present the Desktop Environment Comparison. Just wanted to say that LXQt does not have an "official" Window Manager. While they do have documentation on Openbox, KWin, and Xfwm4 (https://github.com/lxqt/lxqt/wiki/ConfigWindowManagers), it is worth pointing out that Openbox has been abandoned for 9 years. It might be worth listing KWin/Xfwm4. I would suggest KWin since it gets regular updates.  Xfwm4 is only updated every two years. Have a great day. :)

**Comment by eylenburg** [comment]
Thank you, I updated it to mention all three
