### ISSUE TITLE
Browser Comparison Tor, Mulvad Browser, Falkon

### ISSUE THREAD

**Issue by crftbt** [eylenburg/eylenburg.github.io#62]
Is there a chance you would add information on Tor, Mullvad Browser, and Falkon to the Browser Comparison page? :)

**Comment by eylenburg** [comment]
Probably not. I'm currently only comparing browsers that are cross-platform (desktop and mobile) so that excludes Mullvad and Falkon As for Tor browser, I think it's more of a special use browser that you can't really use as your main or only browser. It's not directly competing with the others.
