### ISSUE TITLE
IM comparison: corrections for deltachat

### ISSUE THREAD

**Issue by Simon-Laux** [eylenburg/eylenburg.github.io#63]
I have a few suggestions/corrections for deltachat entry:

- Compatibility with other messengers: if bridges count, deltachat has a plugin for matter bridge: https://github.com/deltachat-bot/matterdelta

- Ephemeral messages, delta chat has that feature, but only for others using DC of course

- contacts from address book: dc can import email addresses, though thats disabled/hidden on [chatmail](https://delta.chat/en/chatmail) accounts, because there you can not send unencrypted messages out, so you can not get in contact with just the email address, you also need the public key

- Domicile of developer: you could say it's developed by merlinux gmbh, Germany - if the other open source projects like element and signal have a company listed so should Delta Chat, I guess.

**Comment by eylenburg** [comment]
Thank you, all updated
