### ISSUE TITLE
Android: "System-wide connection/tracker blocking" allows feature not to be an OS feature

### ISSUE THREAD

**Issue by alohapersona** [eylenburg/eylenburg.github.io#69]
In the feature table "System-wide connection/tracker blocking" has two realizations, "VPN app" and "DNS setting", that refer to features that may or may not be provided through or as part of the OS itself.
- DNS setting for most OS requires the user to find and insert a third-party (or their own) DNS server that would block the trackers for them. In that case, the feature cannot be considered part of the OS. In contrast, the OS vendor could provide their own, tracker-blocking DNS server and make it an easy toggle to enable using that (without having to enter a server address manually), which I then would consider an OS feature. Also one could run a tracker-blocking DNS server on the phone itself, which, if part of the OS, would also be an OS feature.
- VPN apps for blocking trackers can be shipped with the OS or easily provided by the OS vendor (in which case they are an OS feature) or installed from third-parties (in which case they are not).

The way the "System-wide connection/tracker blocking" row works right now, it's pretty useless, as it would be really hard to not be considered supporting this feature (would require removing features from AOSP). It's thus not very helpful for comparison. I would suggest to either entirely remove it, or restrict to functionality that's directly provided by the OS that would block trackers (i.e. not require configuring a server in the settings manually or installing a third-party app).

**Comment by eylenburg** [comment]
Yes, you've got a point, it might be better to just delete this row as it doesn't really tell you anything valuable.

**Comment by alohapersona** [comment]
@matchboxbananasynergy I understand your point, but to a person not knowing, "Private DNS setting, or via VPN app" barely explains how to do it either. And if one searches "How to block trackers on LineageOS" there's probably some reasonable results even without the table giving hints of how it could be done. I would say it's the responsibility of every OS to make sure there is enough and easily found documentation on how to do things like this.

**Comment by alohapersona** [comment]
@eylenburg, sorry for bringing the crusade to your page. I guess every comparison must be designed to be effectively a marketing piece for a specific OS or else their developers and community are immediately going to go after you. I'm closing and unsubscribing here and all the other feedback I had, it's entirely up to you what you do with it and please feel free to ignore it if you don't want to waste your time in discussions like these.

**Comment by eylenburg** [comment]
I think I'll just leave it in as that is the least amount of work and just because AOSP already supports it doesn't mean it can't still be in the table. 

>GrapheneOS update servers have been included on the blocklists used by Quad9 DNS before, because they consume sketchy info as the source for their data and blindly trust it. This puts people in a position to censor the internet stealthily and then claim it was an accident or simply quietly remove it if it goes wrong. (...) If we used Quad9 DNS by default, we would have been at their mercy to fix it or most users wouldn't be able to get updates without undoing that default. Shows how wrong this can go.

This is a very interesting argument against having blocking on by default which I wasn't aware of.
