### ISSUE TITLE
Google EUICC is pre-installed by default on GrapheneOS (but disabled by default)

### ISSUE THREAD

**Issue by notahomosapien** [eylenburg/eylenburg.github.io#7]
Hi
https://eylenburg.github.io/android_comparison.htm currently states that GrapheneOS does not have Google EUICC pre-installed, Which is simply not true. On GrapheneOS, Google EUICC is pre-installed but disabled by default. Google EUICC is only enabled after the user enables the `Privileged eSIM management` toggle.

**Comment by eylenburg** [comment]
Thanks for the correction. This is now fixed.
