### ISSUE TITLE
Android: Update update speed

### ISSUE THREAD

**Issue by alohapersona** [eylenburg/eylenburg.github.io#73]
I suggest to update the update speeds values, which seem to not 100% reflect latest developments. I looked at the last 6 updates of each (based on https://divestos.org/pages/patch_history), here's the suggested changes:

**GrapheneOS**: ~1 day
The March 2024 update was 2 days from Android upstream release, so the previous "<2 days" is technically untrue. I think "~1 day" better reflects it

**DivestOS**: 1-2 weeks
None of the last 6 updates was delayed by more than 14 days (June 2024 update), the average is 9 days.

**CalyxOS**: 2-4 days, sometimes longer
The June 2024 update took 10 days, but all others are less than 4 days, with 3 out of 6 in 2 days. Even when including the 10 days outlier, the average is just below 4 days.

**IodeOS**: 2-4 weeks, sometimes longer
The March 2024 update was skipped and the June 2024 update took 32 days, but the 5 other updates were delivered with 17 to 25 days of delay, the average is 23 if you exclude the skipped update and 29 days if you include it.

**/e/**: 1-2 months, sometimes longer
The March 2024 update was skipped and the June 2024 update is still pending. The other updates took 30-51 days, with 42 days average.

**LineageOS**: 1-2 weeks, sometimes longer
June 2024 update had 18 days of delay, the other 5 between 7 and 12 days. Overall average 11 days

The most notable change to the current list is that CalyxOS seems to be a little faster by now (except for irregular outliers), with 3 out of 6 updates only having 2 days of delay.

**Comment by eylenburg** [comment]
Thank you, that's very useful research. I'll update it in the next few days.

**Comment by alohapersona** [comment]
I'm not suggesting that GrapheneOS is slow, I think the 1 day on average is indeed a very good number, considering the time it takes Google to upload and also that it takes significant time to actually compile Android.

---

You are right that the table does not properly define the details of which parts are updated and how proper the updates are done. The old value was clearly referring to delay between release of upstream and claimed inclusion in update. I was only suggesting to update the numbers based on latest developments, which I think is an easy fix and independent of the other topics you brought up.

**Comment by alohapersona** [comment]
> The data you've gathered above is different for GrapheneOS and non-GrapheneOS. For GrapheneOS, it's referring to when the full Android Security Bulletin and Pixel Security Bulletin patches are applied. For the others, it's referring to when they ship partial Android Security Bulletin patches without the Pixel Security Bulletin patches in most cases.

Just to clarify: You are saying that GrapheneOS shipped ASB patches earlier than 1 day on average and that's not correctly reflected in the table? That's great, would you suggest to write ~0 days instead?

**Comment by eylenburg** [comment]
So @thestinger would it be correct if I changed the name of the row to say something like "Security update speed for Partial Security Updates (ASB)", then using the numbers @alohapersona mentioned and changing GrapheneOS to "same day"?

**Comment by alohapersona** [comment]
@thestinger my data is derived from https://divestos.org/pages/patch_history. This is talking about ASB and proclaimed support by each OS to have it included. According to the table, GrapheneOS included the ASB 2024-03-01 in a build on 2024-03-06, that is 2 days after the ASB was published 2024-03-04 (due to the weekend), so my calculation resulted in 2 days of delay for that month.

Now the question is: Did GrapheneOS have an update before 2024-03-06 that did include the ASB 2024-03-01? If so, you are right, the table is wrong and puts GrapheneOS to a higher standard. If not, and the ASB 2024-03-01 update was provided more than 24 hours after ASB 2024-03-01 was published, < 1 day for GrapheneOS would be incorrect, that's why I suggested ~ 1 day.

**Comment by alohapersona** [comment]
> You're wrong. It was less than 24 hours after it was published.

I haven't done this myself, I'm not the author of https://divestos.org/pages/patch_history, I am just using the data from there. That table claims there is 2 days between ASB publication and GrapheneOS release. That's why I asked if it was less than 24 hours but still displayed as 2 days in the table, which I understand can happen because of timezones.

I'm trying to understand what you say here to provide the possibility to make an accurate assessment and fair comparison possible. Saying "You're wrong" when I ask a question is not really making it easier for me to understand the discrepancies between your numbers and the one from the table.

**Comment by eylenburg** [comment]
I'll re-open this for now because the current row is not 100% correct, especially as it's not distinguishing between the different types of updates. I will need to re-read this discussion and make some of the suggested changes.
