### ISSUE TITLE
CalyxOS: block USB connections default

### ISSUE THREAD

**Issue by lucasmz-dev** [eylenburg/eylenburg.github.io#77]
Small correction, the default in CalyxOS is to block while locked, and is not the same as LineageOS where it is off by default

**Comment by eylenburg** [comment]
Hi, so just to confirm the row `Can disable USB connections?` would have to read `Default (while locked), software only (incomplete)` instead of `Opt-in, software only (incomplete)`?

**Comment by lucasmz-dev** [comment]
Yes
