### ISSUE TITLE
Update "Hosting Virtual Machine" for iOS/iPadOS on OS Comparison page

### ISSUE THREAD

**Issue by GamingHalo975** [eylenburg/eylenburg.github.io#79]
The recent addition of the UTM SE app to the iOS/iPadOS App Store, allowed due to apple ending crackdown on emulators on the App Store, means that you are now able to host virtual machines on iOS/iPadOS without jailbreaking your device. Could include tool tip text stating the lack of JIT.

**Comment by eylenburg** [comment]
Thanks! That's updated
