### ISSUE TITLE
iodeOS - Android Auto

### ISSUE THREAD

**Issue by dktzde** [eylenburg/eylenburg.github.io#82]
iodéOS now supports Android Auto. See here: https://blog.iode.tech/use-android-auto-with-iodeos/

**Comment by eylenburg** [comment]
I added it now. Without information to the contrary, I'll assume it's privileged like on stock Android.

**Comment by dktzde** [comment]
Me too. I asked here
https://community.iode.tech/t/how-is-android-auto-implemented/2924
but did not get an answer yet. If there will be an answer, I will tell you.
