### ISSUE TITLE
CalyxOS update time in the table is inaccurate

### ISSUE THREAD

**Issue by thestinger** [eylenburg/eylenburg.github.io#83]
CalyxOS consistently has weeks of delays for the AOSP security patches, not only days. It should say days to weeks, not 2-4 days. The very unstable security express channel equivalent to the GrapheneOS Alpha channel can't seriously be considered as shipping these patches. Latest example:

https://calyxos.org/news/2024/08/23/august-updates/

This was **not** a quarterly or yearly release but rather a regular monthly release, and regardless the incomplete monthly security backports which is all the table requires are available separately regardless of whether it's a monthly, quarterly or yearly release.

**Comment by eylenburg** [comment]
Updated
