### ISSUE TITLE
add rows for the delays with monthly, quarterly and yearly releases with the full non-device-specific security patches

### ISSUE THREAD

**Issue by thestinger** [eylenburg/eylenburg.github.io#86]
This isn't only about security patches, but shipping the full security patches does require shipping the latest monthly, quarterly and yearly releases. Most alternate operating systems have substantial delays even on Pixels and generally longer delays for non-Pixels. GrapheneOS tends to ship quarterly releases to Stable in around 2 days and yearly releases in under 4 days. Even yearly releases tend to get to Alpha in under 2 days.

**Comment by eylenburg** [comment]
Same here, what would be the delays for each operating system?

**Comment by eylenburg** [comment]
Thanks. I added the row. For IodeOS I used "Several to many months" as they announced their Android 14 upgrade in March 2024 on XDA so shortly after LineageOS. For DivestOS it seems that the latest available download is still based on Android 13 / LineageOS 20.
