### ISSUE TITLE
add Session to IM comparison (pull requests welcome)

### ISSUE THREAD

**Issue by eylenburg** [eylenburg/eylenburg.github.io#95]
[received via emai]

> It has to come to my attention that on your Instant Messenger comparison page (https://eylenburg.github.io/im_comparison.htm), Session is listed among the ones that didn't make it on the list due to - and I quote - "Great privacy, but low adoption".
> 
> I apologize for being downright rude, but that is simply incorrect, as according to to google play (https://play.google.com/store/apps/details?id=network.loki.messenger), it has over one million downloads, and that is just counting android alone.
> 
> Tho I understand how annoying and tedious adding it to the comparison must be, it would be greatly appreciated; but in the end, that choice is ultimately yours to make or not.

**Comment by TimonW-Dev** [comment]
Can this issue be considered resolved with commit [d0b0397](https://github.com/eylenburg/eylenburg.github.io/commit/d0b039724ff94173ca9c135e22d50072982c42de), or is there still something that needs to be addressed?

**Comment by eylenburg** [comment]
All done, you're absolutely right
