### ISSUE TITLE
Fix missing horizontal scrolling in OS Family Tree (pull request welcome)

### ISSUE THREAD

**Issue by eylenburg** [eylenburg/eylenburg.github.io#96]
At the moment you can't scroll the SVG horizontally. No idea why the scrollbar doesn't appear as I'm sure it used to work in the past. I tried nothing and I'm all out of ideas...

https://eylenburg.github.io/os_familytree.htm

**Comment by TimonW-Dev** [comment]
I have opened Pull Request [#101](https://github.com/eylenburg/eylenburg.github.io/pull/101) to solve this problem.
